server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: santhose
    password:
  h2:
    console:
      enabled: true
  security:
    user:
      name: a
      password: b
santhose:
  first: santhose
  last: subramaniam


info:
  app:
    name: Santhose spring boot java learning

management:
  endpoints:
    web:
      expose: "*"
      exposure:
        include: "*"
  security:
    role: SUPERUSER

#security stuff - only actuator endpoint secured and leaves rest for open aceess
